#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"


if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
else
    dir="$PWD"
    while [[ "dir" != "$HOME" && ! -f "$dir/.nvmrc" ]]; do
        dir="$(dirname "$dir")"
    done

    if [[ -f "$dir/.nvmrc" ]]; then
        nvm use "$(cat "$dir/.nvmrc")"
    fi
fi
