#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

desired_version=""

dir="$PWD"
while [[ "$dir" != "$HOME" && ! -f "$dir/.nvmrc" ]]; do
    dir="$(dirname "$dir")"
done

if [[ -f "$dir/.nvmrc" ]]; then
    desired_version="$(cat "$dir/.nvmrc")"
else
    desired_version="$(nvm version default)"
    desired_version="${desired_version:1}"
fi

current_version="$(nvm version)"
current_version="${current_version:1}"

if [[ "$desired_version" != "$current_version" ]]; then
    nvm use "$desired_version"
fi
